### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by CanKolay5677**

### CODE REVIEW

**Comment by CanKolay5677** [comment]
Why I cant see the logs?

**Review by leapofazzam123 — CHANGES_REQUESTED** [review]
Please don't change the tmux screenshot. Also, your edit looks very shitty

**Comment by leapofazzam123** [comment]
Screenshot problem aside, your improvements looks very good

**Comment by CanKolay5677** [comment]
In the screenshot I just changed the notification bar and removed the bottom navigation.

**Comment by leapofazzam123** [comment]
> In the screenshot I just changed the notification bar and removed the bottom navigation.

But it's still a very shitty edit
Screenshot_20211002-180850

**Review by leapofazzam123 — APPROVED** [review]

**Pull request merged**
